name: codecov
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  codecov:
    name: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: run cov
        run: |
          go test ./... -cover -coverprofile=coverage.out
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: .
          files: coverage.out
          fail_ci_if_error: true
          verbose: true
